#! /bin/bash

#!/bin/bash
# Check the spelling of the specified file
cat "$1"
aspell -a -c  < "$1" | grep '^[\&#]' >/tmp/out.$$
# Exit with a non-zero status code if there were any spelling errors because:
# * Finding one or more lines with & or # means we found a spelling error, might be gibberish
if [ $? -ne 0 ]; then
    echo "No spelling errors found; likely correct operation. Success."
    exit 0
fi
cat /tmp/out.$$
echo "Spelling errors found; might indicate garbage output. Failing."
exit 1
