name: Run HQQ tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-hqq:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.g5.4xlarge.nvidia.gpu
      gpu-arch-type: cuda
      gpu-arch-version: "12.1"
      script: |
        echo "::group::Print machine info"
        uname -a
        echo "::endgroup::"

        echo "::group::Install newer objcopy that supports --set-section-alignment"
        yum install -y  devtoolset-10-binutils
        export PATH=/opt/rh/devtoolset-10/root/usr/bin/:$PATH
        echo "::endgroup::"


        echo "::group::Download checkpoints"
        # Install requirements
        ./install_requirements.sh cuda
        bash scripts/build_native.sh aoti
        pip3 list
        python3 -c 'import torch;print(f"torch: {torch.__version__, torch.version.git_version}")'
        yum install -y aspell
        alias check_gibberish='aspell -c --lang=en_US --add-extra-dicts=american-english'
        echo "::endgroup::"

        echo "::group::Download checkpoints"
        mkdir -p checkpoints/stories15M
        pushd checkpoints/stories15M
        wget https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.pt
        wget https://github.com/karpathy/llama2.c/raw/master/tokenizer.model
        popd
        echo "::endgroup::"

        echo "::group::Run inference"
        export MODEL_PATH=checkpoints/stories15M/stories15M.pt
        export MODEL_NAME=stories15M
        export MODEL_DIR=/tmp

        export PROMPT="Once upon a time in a land far away"
        
        for DEVICE in cpu cuda; do 
         for DTYPE in bfloat16 float16 float32; do

          python generate.py --dtype ${DTYPE} --device ${DEVICE} --checkpoint-path ${MODEL_PATH} --temperature 0 > ./output_eager
          check_gibberish ./output_eager
          python generate.py --dtype ${DTYPE} --device ${DEVICE} --compile --checkpoint-path ${MODEL_PATH} --temperature 0 > ./output_compiled
          check_gibberish ./output_compiled
          python export.py --dtype ${DTYPE} --device ${DEVICE} --checkpoint-path ${MODEL_PATH} --output-dso-path ${MODEL_DIR}/${MODEL_NAME}.so
          python generate.py --dtype ${DTYPE} --device ${DEVICE} --checkpoint-path ${MODEL_PATH} --temperature 0 --dso-path ${MODEL_DIR}/${MODEL_NAME}.so  > ./output_aoti
          check_gibberish ./output_aoti

          ./cmake-out/aoti_run ${MODEL_DIR}/${MODEL_NAME}.so  -z ${MODEL_DIR}/tokenizer.model -i "${PROMPT}" > ./output_runner_aoti
          check_gibberish ./output_runner_aoti

          echo "**********************************************"
          echo "******** INT4 HQQ group-wise quantized *******"
          echo "**********************************************"
          python generate.py --dtype ${DTYPE} --device ${DEVICE} --quant '{"linear:hqq" : {"groupsize": 32}}' --checkpoint-path ${MODEL_PATH} --temperature 0 > ./output_eager
          check_gibberish ./output_eager
          python generate.py --dtype ${DTYPE} --device ${DEVICE} --compile --quant '{"linear:hqq" : {"groupsize": 32}}' --checkpoint-path ${MODEL_PATH} --temperature 0 > ./output_compiled
          check_gibberish ./output_compiled
          python export.py --dtype ${DTYPE} --device ${DEVICE} --quant '{"linear:hqq" : {"groupsize": 32}}' --checkpoint-path ${MODEL_PATH} --output-dso-path ${MODEL_DIR}/${MODEL_NAME}.so
          python generate.py --dtype ${DTYPE} --device ${DEVICE} --checkpoint-path ${MODEL_PATH} --temperature 0 --dso-path ${MODEL_DIR}/${MODEL_NAME}.so  > ./output_aoti
          check_gibberish ./output_aoti

          ./cmake-out/aoti_run ${MODEL_DIR}/${MODEL_NAME}.so  -z ${MODEL_DIR}/tokenizer.model -i "${PROMPT}" > ./output_runner_aoti
          check_gibberish ./output_runner_aoti

         done
        done

        echo "tests complete"
        echo "******************************************"
        echo "::endgroup::"
