name: Run compile tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-cuda:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.g5.4xlarge.nvidia.gpu
      docker-image: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime
      script: |
        pip install -r requirements.txt
        python generate.py --compile --cuda
